### ISSUE TITLE
Allow place names as input

### ISSUE THREAD

**Issue by andpersand** [andpersand/iss-notipy#2]
Allow someone to input a place name instead of coordinates.

### to-dos
- [ ] accept place name input
- [ ] convert place name to lat & long
- [ ] pass lat & long to the function
- [ ] (bonus) allow a zip code
