### ISSUE TITLE
Allow custom number of forecasted pass-over dates

### ISSUE THREAD

**Issue by andpersand** [andpersand/iss-notipy#3]
Allow the user to specify how many pass-over dates they want to see.

Currently, the bot will show 5 pass-over dates. This doesn't look great and might be too much info.

### to-dos
- [ ] figure out time zones, conceptually, outside of computers
- [ ] figure out time zones, conceptually, on the computer
- [ ] ask the user for a time zone, OR allow it to be passed as an argument when running the script
